### ISSUE TITLE
Describe how nested containers are (not) handled wrt. limits

### ISSUE THREAD

**Issue by thoni56** [alan-if/alan-docs#111]
As mentioned in https://github.com/alan-if/alan/issues/35# limits are not applied recursively to nested containers.

While we figure out the best course of action (considering aggregating attributes, inheriting limits and many other aspects), at least this should clearly be stated in the manual.

-------------------------------------------------------------------------------

See: [ALAN Manual] » [§3.8 Properties » Limits]

[ALAN Manual]: https://alan-if.github.io/alan-docs/manual-beta/manual.html

[§3.8 Properties » Limits]: https://alan-if.github.io/alan-docs/manual-beta/manual.html#_limits

**Comment by tajmone** [comment]
# Draft PR Created

I've created PR #112 for these changes, and began by polishing and improving the original text, before attempting to add the contents regarding nested containers and LIMITS. 

Thanks to the PR being on a repository branch, we can both keep adding new commits to it, until we're happy with the changes, and then finally squash them into a single commit before merging them into `master`. This also allows to work on the changes on-and-off, without interfering with other developments.
