### ISSUE TITLE
Add Conversion Guide to Website

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#114]
The "ALAN Conversion Guide" is currently not available for download/reading on the GHPages website.

- [x] Add to ALAN Docs website.
- [x] Add links to it in:
    - [x] ALAN Wiki
    - [x] Awesome IF — See: tajmone/awesome-interactive-fiction#20
    - [x] ALAN website.

**Comment by thoni56** [comment]
I've added a `publish.sh` script in the `conversion` subdir that does similar things to the manual (except there are no branch magic).
I've also added an appropriate section to the `index.md` and from the website there is now a link to "All the documents" that goes to the `alan-docs` site.

**Comment by tajmone** [comment]
Great!

> If you find an article or something that mentions conversion, let me know and I'll add a reference there.

I will.
