### ISSUE TITLE
English: British or American?

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#13]
@thoni56 , while editing the Alan Manual I've noticed that sometimes it follows British conventions, other times American conventions. This is probably the result of different people editing the document.

I'm often not sure which convention to follow (e.g., using a comma after _i.e._ and _e.g._, or not), and whenever I need to lookup some grammar or spelling issue (which is rather frequent) I often come across different answers for UK and USA English. This also affects the setting of spell-checking tools, which are quite useful in keeping track of spelling typos and could also ensure that spelling follows either the UK or USA English conventions.

Establishing which English the Manual follows would be a good idea, and we could add it to the guidelines.

What to do you suggest, UK or USA?

**Comment by thoni56** [comment]
The mix is probably only my fault. Since I'm not native speaking I don't have a "natural" feel for all the nuances and wordings that differ. However, I lean towards British spelling ('colour' etc.) when I know that I have to make a conscious decision.

That means my vote goes to British English.

**Comment by tajmone** [comment]
Cool! I'll add it to the Guidelines when I find time, so all tools (spell checkers, etc) can be configured accordingly.

I was born in England, and my family is English from my mother side, and even though I grew up mostly in Italy I've spent over 10 years in the UK, and even went to school there for a while; but my English is getting a bit rusty now, and surely I don't remember much of the grammar rules, except what I picked up by using the language. 

But often it's not easy for me to distinguish between US and UK English, as books, the media and the Internet expose us regularly to both and the boundaries are not so clear today — except maybe for academics or those who write for professional reasons. As for non native English speakers, sticking to one or other is not so easy.

By it's a rather important issue, especially in documentation. For example, while studying Anssi's StdLib support for clothing, I had lot's of trouble with the Clothing Table, because most of the clothing terms mean different things in UK and US English, and I couldn't workout which one they belonged to.

**Comment by thoni56** [comment]
Though as much. Your English is to good for you to be a true Italian ;-)

Then I can disclose that I'm completely on the British side and would like appreciate coaching to become more British in my English. Just installed the British English dictionary to my Firefox on this computer...
