### ISSUE TITLE
Code Styling Conventions

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#2]
I propose that we agree on some code styling conventions for both the manual and other Alan related documents, so that they look consistent in style.

## Code Examples

I think that code examples would be more readable if Alan keywords and built-in classes were in all caps, as it helps distinguish between custom created classes, instances and attributes, versus that which is hard-coded into the language. Currently, first-letter caps styling is being used in the manual.

Example:

```
Every door Isa object
  Has otherside door.
End Every door.

Every lockable_door Isa door.
  Has otherside lockable_door.
End Every lockable_door.

The someDoor Isa door
  Has otherside someLockableDoor.
End The someDoor.

The someLockableDoor Isa lockable_door
  Has otherside someDoor.
End The someLockableDoor.
```

... would become:

```
EVERY door ISA OBJECT
  HAS otherside door.
END EVERY door.

EVERY lockable_door ISA door.
  HAS otherside lockable_door.
END EVERY lockable_door.

THE someDoor ISA door
  HAS otherside someLockableDoor.
END THE someDoor.

THE someLockableDoor ISA lockable_door
  HAS otherside someDoor.
END THE someLockableDoor.
```

Although syntax highlighting is going to mitigate the issue by enforcing special colors to keywords and built-in classes, I nevertheless think that it looks more intuitive for the reader.

Possibly, `ISA` could be capitalized as `IsA`, for readability sake, but the other keywords should be all-caps:

```
EVERY door IsA OBJECT
  HAS otherside door.
END EVERY door.

EVERY lockable_door IsA door.
  HAS otherside lockable_door.
END EVERY lockable_door.

THE someDoor IsA door
  HAS otherside someLockableDoor.
END THE someDoor.

THE someLockableDoor IsA lockable_door
  HAS otherside someDoor.
END THE someLockableDoor.
```

## Inline Keywords

For consistency sake, I'd also style as all caps keywords within paragraphs and other document elements, including headings-titles.

As mentioned in Issue #1, I propose to apply inline-code styling to keywords in paragraphs, but not in headings; but I think they should be at least all-caps in headings, as this will make them stand out in the TOC.

So, reusing the examples from Issue #1:

> Using the **Syntax** construct, you can also define more complex player input.
> 
>  For this purpose, we use **Locations.**

would become:

> Using the `SYNTAX` construct, you can also define more complex player input.
> 
>  For this purpose, we use `LOCATION`s.

## Alan EBNF Blocks

I'd apply the same principle to EBNF blocks (which is already the case, more or less):

```
forms = indefinite | definite | negative

definite = 'DEFINITE' article_or_form

indefinite = [ 'INDEFINITE' ] article_or_form

negative = 'NEGATIVE' article_or_form

article_or_form = 'ARTICLE' {statement}
                | 'FORM' {statement}
```

Although the above styling is not applied to every EBNF block, it seems like this was the preferred styling for EBNF, allowing to easily distinguish between actual keywords and more abstract elements of the syntax.

Here, I'd simply enforce the same styling on all EBNF blocks in the manual.

**Comment by thoni56** [comment]
I really don't like all caps. That's my preference, of course. But to me it is LOUD and in the way of the natural sentences that Alan code is supposed to be. No ONE write SENTENCES this WAY. (I know, noone writes random capitalized words inside sentences either...)

I know that the ALL CAPS styling have somehow stuck since the 80's ;-) even if I try to be adamant about writing all my Alan code examples in Capitalized style...

I would prefer the capitalization of keywords in code.

In EBNF I agree to go for ALL CAPS, because that is the convention for most EBNF grammars I've seen.

**Comment by tajmone** [comment]
I agree 100% on the ugliness of all caps, but my consideration was focused on making it easier for the beginner to distinguish between keywords and native classes and custom classes.

> (I know, noone writes random capitalized words inside sentences either...)

Exactly! the issue really boils down to aesthetics here, and I agree that capitalized is less intrusive than all-caps.

>  It is a built in class, but there is no difference between a builtin class and one that a library defines or the author himself.

The point here is that the examples in the manual are mainly out-of-context snippets, so the casing convention was just intended to make a clear distinction between native and custom elements. I was sharing some considerations from my own experience when I was first reading the various docs, and had found some of the Library documentation easier to sift through because of the all caps convention (especially when sifting through the document quickly, looking for examples).

But then of course syntax highlighting should be enough for this, as it would clarify by color what is what.

Ok, I'll then ensure that keywords are always capitalized in all examples (current and future).

**Comment by tajmone** [comment]
I propose that `Isa` should be capitalized as `IsA` (I'm working on substitutions right now, and have come across this). 

Similarly, `Elsif` should be `ElsIf`, and so on, where keywords that comprise multiple words should be capitalized as if there was a space between them (IMO, easier to read).

**Comment by thoni56** [comment]
Good.

Since the syntaxhighlighting is in our (your) control, could we consider a separate highlighting for built in classes, to make that a bit clearer?

I know we can't be sure about how all backends would handle highlighting. I know that the trick I used for marking lines inside code segments in the guide did not come through to the PDF...

**Comment by tajmone** [comment]
The current Alan syntax I created for Highlight already gives special color to builtin classes (if the user wants to "turn them off" he just needs to assign the same color as "normal" style to them).

> I know we can't be sure about how all backends would handle highlighting.

I haven't yet found the time to look into it closely, but I do fear that some backends might object to it (definitely online services like GitBook and others). But chances are that there are workarounds for it.

In the worst case, I'll build an Alan definition for Rouge, the Ruby highlighter natively supported by Asciidoctor, and that should work with all backends.

Another trick could be to use the PP preprocessor and resort to macros to handle highlighting _before_ feeding the source doc to AsciiDoctor, and have the macro produce format-specific raw blocks that AsciiDoc should just pass through (either HTML, XML, TeX, or whatever).

But I'd like to keep the whole thing simple, and as close to AsciiDoc standards as possibile, so looking into a new Rouge syntax might be best.
