### ISSUE TITLE
TBD Manual: G.3. Player words

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#26]
[Appendix G: Localization], section _[G.3. Player words]_.

Marked as TBD in original Manual.

Live preview from `dev-man`:

- [§G.3. _Player words_][G.3. dev] (`dev-man`)

[Appendix G: Localization]: https://htmlpreview.github.io/?https://github.com/alan-if/alan-docs/blob/master/manual/manual.html#_localization "HTML live preview link"
[G.3. Player words]: https://htmlpreview.github.io/?https://github.com/alan-if/alan-docs/blob/master/manual/manual.html#_player_words "HTML live preview link"
[G.3. dev]: https://htmlpreview.github.io/?https://github.com/alan-if/alan-docs/blob/dev-man/manual/manual.html#_player_words "HTML live preview from 'dev-man'"

**Comment by tajmone** [comment]
Currently being worked-on in branch [`AppG-i18n`][AppG-i18n].

Live HTML Preview link:

- https://htmlpreview.github.io/?https://github.com/alan-if/alan-docs/blob/AppG-i18n/manual/manual.html#_player_words

[AppG-i18n]: https://github.com/alan-if/alan-docs/tree/AppG-i18n/manual

**Comment by thoni56** [comment]
I suppose this can be closed?
