### ISSUE TITLE
ALAN Manual: Switch to Highlight

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#50]
Currently the only reason why we are not using Highlight for the _Alan Manual_ is because it uses callouts in a few places, which are not yet supported in the Highlight extension for Asciidoctor.

See Issue #36 for more details on the problem.

> **IMPORTANT!** — See also proposal #107 to switch to [Rouge](http://rouge.jneen.net) instead!

> **~~IMPORTANT!~~** — ~~If we switch to Highlight, we need to check for the presence of code blocks with an indented 1st line, and apply the fixes of #70~~.
> > **EDITED** — This problem was fixed at the template level, in commit aa8fb6529e5f328ed68e7f0dbf385f7477491b9d.

> **EDITED** — The above information is actually incorrect! The _Manual_ currently only uses callouts in [App. F.1. _Format of Messages_][F1], for a shell/CMD literal block, which is not being syntax highlighted!
>
> So __*we could*__ simply switch to Highlight at any moment, without breaking the document. This would allow us to have syntax highlighted code in the HTML Live Preview link, which is currently used by ALAN website to direct end users to the online manual.
>
> Of course, after the switch to the Asciidoctor format we were hoping to use callouts freely in the Manual, for they are great references for commenting the code examples in a clean way. But in the meantime, while awaiting to a switch to the Rogue highlighter, we could just switch temporarily to Highlight, so that:
>
> 1. ~~The Live HTML Preview will be syntax colored~~. (_no longer applies now that we have a real website!_)
> 2. We can benefit from static highlighting for better HTML chunking (sse #78).

[F1]: https://htmlpreview.github.io/?https://github.com/alan-if/alan-docs/blob/master/manual/manual.html#_format_of_messages

**Comment by tajmone** [comment]
@thoni56, what do you think, should we just switch from highlight.js to Highlight?

The immediate benefits are:

- Fully standalone HTML document (no dependencies beside the web fonts).
- Easier maintenance of shared Sass/CSS stylesheets for all Alan docs.
- We can finally create an executable eBook version (MS Win only).

The downside:

- Can't use callouts in highlighted listing blocks.

In the future we might switch to Rouge highlighter (Ruby) which is fully supported by Asciidoctor (HTML and native PDF backends), but I'm still looking into it right now — the problem is not creating the ALAN syntax, but using it with Asciidoctor without the syntax being accepted in the official Rouge repo (Gem); I'm not sure how custom syntaxes that are officially part of Rouge can be enforced on the Asciidoctor toolchain (or if it's even doable at all).

Unfortunately, I don't have enough Ruby/Asciidoctor knowledge to fix the current Highlight extension to support callouts (see #36).

**Comment by thoni56** [comment]
The advantages seems to be greater than the downsides, so I think we should. If the callouts in Appendix F is not possible to fix we can do that some other way, like simply numbering the lines and refering to those. A bit less elegant but still good enough.

**Comment by tajmone** [comment]
The callouts in App. F are fine because it's not an highlighted block, just a styled verbatim block.

**Comment by tajmone** [comment]
# Dropped! 

Switched to Rouge Instead .... the rest is history.
