### ISSUE TITLE
Sec Nums Out of Synch between HTML and PDF Manual

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#68]
Either:

- [ ] Fix numbering in PDF doc.
- [ ] Remove `:sectnums!:` suppression in source document.

Sections numbers between the HTML and PDF docs are out of synch: e.g. "§3.1. _General Rules_" of the HTML doc is §3.2 in the PDF document.

This seems to be due to the temporary suppression of `sectnums` for some sections. From the §3.1 example mentioned above, we find in `manual_03.asciidoc`:

```asciidoc
:sectnums!:
== General Rules

The Alan language is [...]

:sectnums:
== An Adventure
```

which was intended to suppress the sec.num. for the intruoductiory sec. "General Rules", and start over from the next sec. This works as excpected in the HTML doc, but not so in the PDF version, which apprarently ignores the `:sectnums!:` attribute directive.

__NOTE__ — Suppression of sec.num. in certain sections was done for legacy reasons, because the original ODT/PDF _Manual_ did so. It was intended to preserve section numbering across various editions as close as possible — although this might not be possible due to the introudction of new sections.

**Comment by tajmone** [comment]
Issue created on asciidoctor-fopub for this problem:

- asciidoctor/asciidoctor-fopub#98

**Comment by thoni56** [comment]
Yeah. Let's go with your suggestion, @tajmone.

**Comment by tajmone** [comment]
Great! And a huge thank to @mojavelinux for having kindly joined in and helped us out of this conondrum!
