### ISSUE TITLE
Spurious Diagram Images in 'published' Branch

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#97]
@thoni56, I've noticed that the `published` branch contains a couple of images from the _[Alan Design Documentation]_:

- `dictionary-entry.png`
- `stack-machine.png`

both images were generated via the asciidoctor-diagram gem.

Since the document is built using the `-a data-uri` option (attribute), all images stored on disk are automatically embedded into the HTML document via Base64 encoded Data-URIs, so the document is fully standalone (and downloadable via "Save As").

So we could safely delete those images, unless you need them for some other purpose (e.g. because you're linking them from elsewhere, to embed them in some other on-line document or post).

[Alan Design Documentation]: https://alan-if.github.io/alan-docs/design/design.html

**Comment by thoni56** [comment]
Yes, they are ok to delete. They are probably residue from the initial tests with the published branch when I had to re-do it a couple of times and generated the documents by hand.
